# Generated by Django 3.1.7 on 2021-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageParking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='postcode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='vacant',
            field=models.BooleanField(blank=True),
        ),
    ]
