# Generated by Django 3.1.7 on 2021-07-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageParking', '0002_auto_20210421_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='date_modified',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='date_modified',
            field=models.DateField(null=True),
        ),
    ]
