# Generated by Django 3.1.7 on 2021-07-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageParking', '0004_auto_20210721_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parking',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
