# Generated by Django 3.1.7 on 2021-09-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageParking', '0006_auto_20210914_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='canvas',
            field=models.JSONField(null=True),
        ),
    ]
