# Generated by Django 3.2.8 on 2022-02-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageParking', '0009_alter_parking_canvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='img',
            field=models.CharField(default='PUCPR', max_length=10),
            preserve_default=False,
        ),
    ]
