# Generated by Django 3.2.8 on 2022-02-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageParking', '0011_alter_parking_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='img',
            field=models.CharField(choices=[('PUCPR', 'PUCPR'), ('UFPR04', 'UFPR04'), ('UFPR05', 'UFPR05')], max_length=10),
        ),
    ]
